[package]
name = "thenexusavenger/nexus-admin"
repository = "https://github.com/TheNexusAvenger/Nexus-Admin"
description = "Admin system for Roblox meant for normal players. Built on top of evaera/Cmdr."
license = "MIT"
authors = ["TheNexusAvenger"]
version = "2.10.3"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["dist", "dist/*", "src", "src/*", "MainModule.luau", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
NexusButton = "thenexusavenger/nexus-button@2.5.2"
NexusDataStore = "thenexusavenger/nexus-data-store@1.6.2"
NexusFeatureFlags = "thenexusavenger/nexus-feature-flags@1.3.2"
NexusInstance = "thenexusavenger/nexus-instance@4.1.2"
NexusVirtualList = "thenexusavenger/nexus-virtual-list@1.1.0"